
//// Swapping tables

// Setting up dev table
CREATE TRANSIENT SCHEMA OUR_FIRST_DB.COPIED_SCHEMA
CLONE OUR_FIRST_DB.PUBLIC;

SELECT * FROM OUR_FIRST_DB.COPIED_SCHEMA.CUSTOMERS;
SELECT * FROM OUR_FIRST_DB.PUBLIC.CUSTOMERS;


// Modifying "Dev Table"
DELETE FROM OUR_FIRST_DB.COPIED_SCHEMA.CUSTOMERS WHERE ID < 500

SELECT * FROM OUR_FIRST_DB.COPIED_SCHEMA.CUSTOMERS


// Swapping Tables
ALTER TABLE OUR_FIRST_DB.COPIED_SCHEMA.CUSTOMERS
SWAP WITH OUR_FIRST_DB.PUBLIC.CUSTOMERS

// Verifying results
SELECT * FROM OUR_FIRST_DB.COPIED_SCHEMA.CUSTOMERS
SELECT * FROM OUR_FIRST_DB.PUBLIC.CUSTOMERS

/*******************************ASSIGNMENT******************************/

CREATE OR REPLACE TABLE SUPPLIER
AS
SELECT * FROM "SNOWFLAKE_SAMPLE_DATA"."TPCH_SF1"."SUPPLIER";

CREATE TABLE Suppler_second_clone 
CLONE Suppler_clone before (statement => '01bff85a-0003-bb51-000a-0ba2000136ce')

SELECT * FROM Suppler_second_clone 

--Update the clone table and copy the query id

UPDATE SUPPLeR_CLONE
SET S_PHONE='###';
 
--> Query ID:

